### ISSUE TITLE
Installation crashes

### ISSUE THREAD

**Issue by WebPlanning** [happilymarrieddad/sc-crud-mysql#1]
Hi There

I've being trying to install that component; but unfortunately it is impossible.

Indeed whenever i try an installation I got so many errors and no matter If I run command via sudo. (Please have a glance at those pictures)

Thus, I cannot try this out. It sound's really cool but impossible to evaluate it..

Could you may give me help on the installation?

Cheers

![sc-crud-mysql - 001](https://user-images.githubusercontent.com/12293203/56081195-f2efda80-5e0a-11e9-8176-40ee3832ca4e.png)
![sc-crud-mysql - 002](https://user-images.githubusercontent.com/12293203/56081196-f2efda80-5e0a-11e9-8f09-9367092c24b7.png)

**Comment by happilymarrieddad** [comment]
What version of Node are you using? Unfortunately, I built this library a long time ago and I'm betting it's a node version problem. I'm pretty sure I tested it with Node 4.

**Comment by happilymarrieddad** [comment]
@PatDav
